version: '3.8'

services:
  react-app:
    image: react-docker-secrets:production
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    secrets:
      - REACT_APP_NAME
      - REACT_APP_API_URL
      - REACT_APP_ENVIRONMENT
      - REACT_APP_VERSION
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  REACT_APP_NAME:
    external: true
  REACT_APP_API_URL:
    external: true
  REACT_APP_ENVIRONMENT:
    external: true
  REACT_APP_VERSION:
    external: true

networks:
  default:
    driver: overlay
    attachable: true